from .alumno_service import AlumnoService
from .area_service import AreaService
from .autoridad_service import AutoridadService
from .cargo_service import CargoService
from .categoriacargo_service import CategoriaCargoService
from .departamento_service import DepartamentoService
from .especialidad_service import EspecialidadService
from .facultad_service import FacultadService
from .grado_service import GradoService
from .grupo_service import GrupoService
from .materia_service import MateriaService
from .orientacion_service import OrientacionService
from .plan_service import PlanService
from .tipodedicacion_service    import TipoDedicacionService
from .tipodocumento_service import TipoDocumentoService
from .tipoespecialidad_service import TipoEspecialidadService
from .universidad_service import UniversidadService